# a = ['S_ASSETCLS', "S_MAINCONT';\n", "MAINCONT';\n", 'COLL_ACCOUNTS', 'S_LNACGUAR', "COLL_ACCOUNTS';\n", 'IACLINK', 'ACNTS', 'CLIENTS', 'S_IACLINK', 'S_MBRN', 'S_LNPRODPM', 'S_LNACRSDTL', 'S_LNACRSDTL', 'S_LNACDISB', 'S_LNACDISB', 'S_LNACIR', 'S_PRODIR', 'S_ACNTBAL', 'S_LNWRTOFF', 'S_LNWRTOFF', 'S_TRAN', 'COLL_ACCOUNTS', 'S_ACNTS', 'S_INDCLIENTS', 'S_CLIENTS', 'S_PIDDOCS', 'COLL_CUSTOMER', 'S_LANGUAGES', 'S_CNTRY', 'S_OCCUPATIONS', 'S_DESIGNATIONS', 'S_CLIENTSBKDTL', 'S_USERS', 'S_LOCATION', 'S_CLIENTS', 'S_LOCATION', 'S_INDCLIENTS', 'S_LNWRTOFF', 'S_ACNTS', 'S_ACASLLDTL', 'S_SECASSIGNMTBAL', 'S_SECRCPT', 'S_CLIENTS', 'S_SECVEHICLE', 'S_SECVAL', 'S_SECVAL', 'S_SECINSUR', 'S_INSUCMP', 'S_TRANCD', 'S_OCLGINST', 'S_CLIENTS', 'S_SECCLIENT', "LNACDLYAGING'", 'S_PRODAMORT))', 'COLL_DB_LINK', "EXT_COL_FINDETAILS@'", "ext_col_bounce@'", "EXT_COL_AGREEMENT@'", "EXT_COL_CUSTOMER@'", "EXT_COL_CUSTOMERADDRESS@'", "EXT_COL_AGRCUSTXREF@'", "EXT_COL_AGRCHARGES@'", "EXT_COL_ASSET@'", "EXT_COL_MASTERS@'", "EXT_COL_AGEING@'", 'FINDETAILS', 'BOUNCE', 'CUSTOMER', 'CUSTADDR', 'AGRCUSTXREF', 'AGRCHARGES', 'ASSET', 'MASTERS', 'AGEING', 'AGREEMENT', 'CUSTOMER', 'CUSTADDR', 'AGRCUSTXREF', 'AGRCHARGES', 'ASSET', 'FINDETAILS', 'BOUNCE', "LNACDLYOD'", "LNACDLYOD'", "LNACDLYOD'", 'COLL_ACCOUNTS', 'S_ACNTS', 'COLL_PRODUCTS', 'COLL_ACCOUNTS', 'S_ACNTS', 'COLL_PRODUCTS', 'COLL_ACCOUNTS', "LNACDLYOD'", 'COLL_ACCOUNTS', "LNACDLYOD'", 'COLL_ACCOUNTS', "LNACDLYOD'", 'COLL_ACCOUNTS', "LNACDLYOD'", "LNACDLYOD'", "LNACDLYOD'", "LNACDLYOD'", "LNACDLYOD'", 'S_ACNTS', 'S_ACNTS', "LNACDLYOD'", 'COLL_PRODUCTS', 'COLL_ACCOUNTS', 'DUAL;\n', "LNACDLYOD'", "LNACDLYOD'", "TRAN'||V_FIN_YEAR", "S_TRAN'", "TRAN'||V_FIN_YEAR", "LNACDLYOD'", 'AGREEMENT', 'COLL', 'COLL', 'S_PRODAMORT', 'S_LNACRS', 'S_ACNTS', "S_TRAN'", 'LOANODAPPL', "LNACDLYOD'", "DUAL';\n", 'AGRCHARGES', 'AGRCHARGES', 'AGRCHARGES', 'AGRCHARGES', 'AGRCHARGES', 'S_SECASSIGNMTBAL\n', "S_TRAN'", 'FINDETAILS', 'S_PRODGROUPS', 'S_PRODIR', 'S_CHGCD', 'S_SECTYPES', 'S_COMPANIES', 'S_MBRN', 'S_LOCATION', 'S_SCHEME', 'S_MKTCHANNEL', 'S_LANGUAGES', 'MASTERS', "MASTERS)';\n", 'S_CLIENTS', 'DUAL;\n', 'S_ACNTS', 'PRDWISESTATUSDTL', 'PRDWISESTATUSDTL']
# b= dict.fromkeys(a)
# print(b)
# faces_phrase = '<faces-config>'
# faces_config_file = 'E:\\Priya\\TechUpgrade\\Repo\\csbcm-rebase\\Panaceaweb\\WebContent\\ADV\\faces-config.xml'
# with open(faces_config_file,'r+') as f:
#     data = f.readlines()
#     for (i,line) in enumerate(data):
#         if faces_phrase in line:
#             index = i
#             break
#     data.insert(i+1,'<new> \n')
#     f.seek(0)
#     f.writelines(data)
label_message_file = 'E:\\Priya\\TechUpgrade\\Repo\\csbcm-rebase\\Panaceaweb\\src\\panaceaADVweb\\advMsg\\LabelMsg.properties'